version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jacoco-maven-plugin"
        versions: ["0.8.x"]
      - dependency-name: "maven-invoker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
