/*
 * Cloud Manager API
 * This API allows access to Cloud Manager programs, pipelines, and environments by an authorized technical account created through the Adobe I/O Console. The base url for this API is https://cloudmanager.adobe.io, e.g. to get the list of programs for an organization, you would make a GET request to https://cloudmanager.adobe.io/api/programs (with the correct set of headers as described below). This swagger file can be downloaded from https://raw.githubusercontent.com/AdobeDocs/cloudmanager-api-docs/main/swagger-specs/api.yaml.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.adobe.aio.cloudmanager.impl.model;

/*-
 * #%L
 * Adobe Cloud Manager Client Library
 * %%
 * Copyright (C) 2020 - 2022 Adobe Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import java.util.Arrays;
import com.adobe.aio.cloudmanager.impl.model.IPAllowedListBinding;
import com.adobe.aio.cloudmanager.impl.model.IPAllowedListLinks;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * Describes an __IP Allowed List__
 */
@Schema(description = "Describes an __IP Allowed List__")

public class IPAllowedList implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("ipCidrSet")
  private List<String> ipCidrSet = new ArrayList<>();

  @JsonProperty("programId")
  private String programId = null;

  @JsonProperty("bindings")
  private List<IPAllowedListBinding> bindings = null;

  @JsonProperty("_links")
  private IPAllowedListLinks _links = null;

  public IPAllowedList id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the IP Allowed List
   * @return id
  **/
  @Schema(example = "14", description = "Identifier of the IP Allowed List")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IPAllowedList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the IP Allowed List
   * @return name
  **/
  @Schema(example = "NewYork Office", required = true, description = "Name of the IP Allowed List")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IPAllowedList ipCidrSet(List<String> ipCidrSet) {
    this.ipCidrSet = ipCidrSet;
    return this;
  }

  public IPAllowedList addIpCidrSetItem(String ipCidrSetItem) {
    this.ipCidrSet.add(ipCidrSetItem);
    return this;
  }

   /**
   * IP CIDR Set
   * @return ipCidrSet
  **/
  @Schema(example = "[\"11.22.33.44/28\", \"99.88.77.66/32\"]", required = true, description = "IP CIDR Set")
  public List<String> getIpCidrSet() {
    return ipCidrSet;
  }

  public void setIpCidrSet(List<String> ipCidrSet) {
    this.ipCidrSet = ipCidrSet;
  }

  public IPAllowedList programId(String programId) {
    this.programId = programId;
    return this;
  }

   /**
   * Identifier of the program.
   * @return programId
  **/
  @Schema(example = "22", description = "Identifier of the program.")
  public String getProgramId() {
    return programId;
  }

  public void setProgramId(String programId) {
    this.programId = programId;
  }

  public IPAllowedList bindings(List<IPAllowedListBinding> bindings) {
    this.bindings = bindings;
    return this;
  }

  public IPAllowedList addBindingsItem(IPAllowedListBinding bindingsItem) {
    if (this.bindings == null) {
      this.bindings = new ArrayList<>();
    }
    this.bindings.add(bindingsItem);
    return this;
  }

   /**
   * IP Allowlist bindings
   * @return bindings
  **/
  @Schema(description = "IP Allowlist bindings")
  public List<IPAllowedListBinding> getBindings() {
    return bindings;
  }

  public void setBindings(List<IPAllowedListBinding> bindings) {
    this.bindings = bindings;
  }

  public IPAllowedList _links(IPAllowedListLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public IPAllowedListLinks getLinks() {
    return _links;
  }

  public void setLinks(IPAllowedListLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPAllowedList ipAllowedList = (IPAllowedList) o;
    return Objects.equals(this.id, ipAllowedList.id) &&
        Objects.equals(this.name, ipAllowedList.name) &&
        Objects.equals(this.ipCidrSet, ipAllowedList.ipCidrSet) &&
        Objects.equals(this.programId, ipAllowedList.programId) &&
        Objects.equals(this.bindings, ipAllowedList.bindings) &&
        Objects.equals(this._links, ipAllowedList._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, ipCidrSet, programId, bindings, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPAllowedList {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ipCidrSet: ").append(toIndentedString(ipCidrSet)).append("\n");
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("    bindings: ").append(toIndentedString(bindings)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
