/*
 * Cloud Manager API
 * This API allows access to Cloud Manager programs, pipelines, and environments by an authorized technical account created through the Adobe I/O Console. The base url for this API is https://cloudmanager.adobe.io, e.g. to get the list of programs for an organization, you would make a GET request to https://cloudmanager.adobe.io/api/programs (with the correct set of headers as described below). This swagger file can be downloaded from https://raw.githubusercontent.com/AdobeDocs/cloudmanager-api-docs/main/swagger-specs/api.yaml.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.adobe.aio.cloudmanager.impl.model;

/*-
 * #%L
 * Adobe Cloud Manager Client Library
 * %%
 * Copyright (C) 2020 - 2022 Adobe Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * A representation of a specific metric generated by a CI/CD Pipeline step.
 */
@Schema(description = "A representation of a specific metric generated by a CI/CD Pipeline step.")

public class Metric implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("id")
  private String id = null;

  /**
   * Severity of the metric
   */
  public enum SeverityEnum {
    CRITICAL("critical"),
    IMPORTANT("important"),
    INFORMATIONAL("informational");

    private String value;

    SeverityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SeverityEnum fromValue(String text) {
      for (SeverityEnum b : SeverityEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("severity")
  private SeverityEnum severity = null;

  @JsonProperty("passed")
  private Boolean passed = false;

  @JsonProperty("override")
  private Boolean override = false;

  @JsonProperty("actualValue")
  private String actualValue = null;

  @JsonProperty("expectedValue")
  private String expectedValue = null;

  /**
   * Comparator used for the metric
   */
  public enum ComparatorEnum {
    GT("GT"),
    GTE("GTE"),
    LT("LT"),
    LTE("LTE"),
    EQ("EQ"),
    NEQ("NEQ");

    private String value;

    ComparatorEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ComparatorEnum fromValue(String text) {
      for (ComparatorEnum b : ComparatorEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("comparator")
  private ComparatorEnum comparator = null;

  @JsonProperty("kpi")
  private String kpi = null;

  public Metric id(String id) {
    this.id = id;
    return this;
  }

   /**
   * KPI result identifier
   * @return id
  **/
  @Schema(description = "KPI result identifier")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Metric severity(SeverityEnum severity) {
    this.severity = severity;
    return this;
  }

   /**
   * Severity of the metric
   * @return severity
  **/
  @Schema(description = "Severity of the metric")
  public SeverityEnum getSeverity() {
    return severity;
  }

  public void setSeverity(SeverityEnum severity) {
    this.severity = severity;
  }

  public Metric passed(Boolean passed) {
    this.passed = passed;
    return this;
  }

   /**
   * Whether metric is considered passed
   * @return passed
  **/
  @Schema(description = "Whether metric is considered passed")
  public Boolean isPassed() {
    return passed;
  }

  public void setPassed(Boolean passed) {
    this.passed = passed;
  }

  public Metric override(Boolean override) {
    this.override = override;
    return this;
  }

   /**
   * Whether user override the failed metric
   * @return override
  **/
  @Schema(description = "Whether user override the failed metric")
  public Boolean isOverride() {
    return override;
  }

  public void setOverride(Boolean override) {
    this.override = override;
  }

  public Metric actualValue(String actualValue) {
    this.actualValue = actualValue;
    return this;
  }

   /**
   * Expected value for the metric
   * @return actualValue
  **/
  @Schema(description = "Expected value for the metric")
  public String getActualValue() {
    return actualValue;
  }

  public void setActualValue(String actualValue) {
    this.actualValue = actualValue;
  }

  public Metric expectedValue(String expectedValue) {
    this.expectedValue = expectedValue;
    return this;
  }

   /**
   * Expected value for the metric
   * @return expectedValue
  **/
  @Schema(description = "Expected value for the metric")
  public String getExpectedValue() {
    return expectedValue;
  }

  public void setExpectedValue(String expectedValue) {
    this.expectedValue = expectedValue;
  }

  public Metric comparator(ComparatorEnum comparator) {
    this.comparator = comparator;
    return this;
  }

   /**
   * Comparator used for the metric
   * @return comparator
  **/
  @Schema(description = "Comparator used for the metric")
  public ComparatorEnum getComparator() {
    return comparator;
  }

  public void setComparator(ComparatorEnum comparator) {
    this.comparator = comparator;
  }

  public Metric kpi(String kpi) {
    this.kpi = kpi;
    return this;
  }

   /**
   * KPI identifier
   * @return kpi
  **/
  @Schema(description = "KPI identifier")
  public String getKpi() {
    return kpi;
  }

  public void setKpi(String kpi) {
    this.kpi = kpi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metric metric = (Metric) o;
    return Objects.equals(this.id, metric.id) &&
        Objects.equals(this.severity, metric.severity) &&
        Objects.equals(this.passed, metric.passed) &&
        Objects.equals(this.override, metric.override) &&
        Objects.equals(this.actualValue, metric.actualValue) &&
        Objects.equals(this.expectedValue, metric.expectedValue) &&
        Objects.equals(this.comparator, metric.comparator) &&
        Objects.equals(this.kpi, metric.kpi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, severity, passed, override, actualValue, expectedValue, comparator, kpi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metric {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    passed: ").append(toIndentedString(passed)).append("\n");
    sb.append("    override: ").append(toIndentedString(override)).append("\n");
    sb.append("    actualValue: ").append(toIndentedString(actualValue)).append("\n");
    sb.append("    expectedValue: ").append(toIndentedString(expectedValue)).append("\n");
    sb.append("    comparator: ").append(toIndentedString(comparator)).append("\n");
    sb.append("    kpi: ").append(toIndentedString(kpi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
