/*
 * Cloud Manager API
 * This API allows access to Cloud Manager programs, pipelines, and environments by an authorized technical account created through the Adobe I/O Console. The base url for this API is https://cloudmanager.adobe.io, e.g. to get the list of programs for an organization, you would make a GET request to https://cloudmanager.adobe.io/api/programs (with the correct set of headers as described below). This swagger file can be downloaded from https://raw.githubusercontent.com/AdobeDocs/cloudmanager-api-docs/main/swagger-specs/api.yaml.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.adobe.aio.cloudmanager.impl.model;

/*-
 * #%L
 * Adobe Cloud Manager Client Library
 * %%
 * Copyright (C) 2020 - 2022 Adobe Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import java.util.Arrays;
import com.adobe.aio.cloudmanager.impl.model.NetworkInfrastructure;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * NetworkInfrastructuresListEmbedded
 */


public class NetworkInfrastructuresListEmbedded implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("networkInfrastructures")
  private List<NetworkInfrastructure> networkInfrastructures = null;

  public NetworkInfrastructuresListEmbedded networkInfrastructures(List<NetworkInfrastructure> networkInfrastructures) {
    this.networkInfrastructures = networkInfrastructures;
    return this;
  }

  public NetworkInfrastructuresListEmbedded addNetworkInfrastructuresItem(NetworkInfrastructure networkInfrastructuresItem) {
    if (this.networkInfrastructures == null) {
      this.networkInfrastructures = new ArrayList<>();
    }
    this.networkInfrastructures.add(networkInfrastructuresItem);
    return this;
  }

   /**
   * Get networkInfrastructures
   * @return networkInfrastructures
  **/
  @Schema(description = "")
  public List<NetworkInfrastructure> getNetworkInfrastructures() {
    return networkInfrastructures;
  }

  public void setNetworkInfrastructures(List<NetworkInfrastructure> networkInfrastructures) {
    this.networkInfrastructures = networkInfrastructures;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkInfrastructuresListEmbedded networkInfrastructuresListEmbedded = (NetworkInfrastructuresListEmbedded) o;
    return Objects.equals(this.networkInfrastructures, networkInfrastructuresListEmbedded.networkInfrastructures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkInfrastructures);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkInfrastructuresListEmbedded {\n");
    
    sb.append("    networkInfrastructures: ").append(toIndentedString(networkInfrastructures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
