/*
 * Cloud Manager API
 * This API allows access to Cloud Manager programs, pipelines, and environments by an authorized technical account created through the Adobe I/O Console. The base url for this API is https://cloudmanager.adobe.io, e.g. to get the list of programs for an organization, you would make a GET request to https://cloudmanager.adobe.io/api/programs (with the correct set of headers as described below). This swagger file can be downloaded from https://raw.githubusercontent.com/AdobeDocs/cloudmanager-api-docs/main/swagger-specs/api.yaml.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.adobe.aio.cloudmanager.impl.model;

/*-
 * #%L
 * Adobe Cloud Manager Client Library
 * %%
 * Copyright (C) 2020 - 2022 Adobe Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import java.util.Arrays;
import com.adobe.aio.cloudmanager.impl.model.HalLink;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * ProgramLinks
 */


public class ProgramLinks implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("http://ns.adobe.com/adobecloud/rel/pipelines")
  private HalLink httpnsAdobeComadobecloudrelpipelines = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/environments")
  private HalLink httpnsAdobeComadobecloudrelenvironments = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/repositories")
  private HalLink httpnsAdobeComadobecloudrelrepositories = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/ipAllowlists")
  private HalLink httpnsAdobeComadobecloudrelipAllowlists = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/certificates")
  private HalLink httpnsAdobeComadobecloudrelcertificates = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/domainNames")
  private HalLink httpnsAdobeComadobecloudreldomainNames = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/tenant")
  private HalLink httpnsAdobeComadobecloudreltenant = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/networkInfrastructures")
  private HalLink httpnsAdobeComadobecloudrelnetworkInfrastructures = null;

  @JsonProperty("http://ns.adobe.com/adobecloud/rel/regions")
  private HalLink httpnsAdobeComadobecloudrelregions = null;

  @JsonProperty("self")
  private HalLink self = null;

  public ProgramLinks httpnsAdobeComadobecloudrelpipelines(HalLink httpnsAdobeComadobecloudrelpipelines) {
    this.httpnsAdobeComadobecloudrelpipelines = httpnsAdobeComadobecloudrelpipelines;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelpipelines
   * @return httpnsAdobeComadobecloudrelpipelines
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelpipelines() {
    return httpnsAdobeComadobecloudrelpipelines;
  }

  public void setHttpnsAdobeComadobecloudrelpipelines(HalLink httpnsAdobeComadobecloudrelpipelines) {
    this.httpnsAdobeComadobecloudrelpipelines = httpnsAdobeComadobecloudrelpipelines;
  }

  public ProgramLinks httpnsAdobeComadobecloudrelenvironments(HalLink httpnsAdobeComadobecloudrelenvironments) {
    this.httpnsAdobeComadobecloudrelenvironments = httpnsAdobeComadobecloudrelenvironments;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelenvironments
   * @return httpnsAdobeComadobecloudrelenvironments
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelenvironments() {
    return httpnsAdobeComadobecloudrelenvironments;
  }

  public void setHttpnsAdobeComadobecloudrelenvironments(HalLink httpnsAdobeComadobecloudrelenvironments) {
    this.httpnsAdobeComadobecloudrelenvironments = httpnsAdobeComadobecloudrelenvironments;
  }

  public ProgramLinks httpnsAdobeComadobecloudrelrepositories(HalLink httpnsAdobeComadobecloudrelrepositories) {
    this.httpnsAdobeComadobecloudrelrepositories = httpnsAdobeComadobecloudrelrepositories;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelrepositories
   * @return httpnsAdobeComadobecloudrelrepositories
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelrepositories() {
    return httpnsAdobeComadobecloudrelrepositories;
  }

  public void setHttpnsAdobeComadobecloudrelrepositories(HalLink httpnsAdobeComadobecloudrelrepositories) {
    this.httpnsAdobeComadobecloudrelrepositories = httpnsAdobeComadobecloudrelrepositories;
  }

  public ProgramLinks httpnsAdobeComadobecloudrelipAllowlists(HalLink httpnsAdobeComadobecloudrelipAllowlists) {
    this.httpnsAdobeComadobecloudrelipAllowlists = httpnsAdobeComadobecloudrelipAllowlists;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelipAllowlists
   * @return httpnsAdobeComadobecloudrelipAllowlists
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelipAllowlists() {
    return httpnsAdobeComadobecloudrelipAllowlists;
  }

  public void setHttpnsAdobeComadobecloudrelipAllowlists(HalLink httpnsAdobeComadobecloudrelipAllowlists) {
    this.httpnsAdobeComadobecloudrelipAllowlists = httpnsAdobeComadobecloudrelipAllowlists;
  }

  public ProgramLinks httpnsAdobeComadobecloudrelcertificates(HalLink httpnsAdobeComadobecloudrelcertificates) {
    this.httpnsAdobeComadobecloudrelcertificates = httpnsAdobeComadobecloudrelcertificates;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelcertificates
   * @return httpnsAdobeComadobecloudrelcertificates
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelcertificates() {
    return httpnsAdobeComadobecloudrelcertificates;
  }

  public void setHttpnsAdobeComadobecloudrelcertificates(HalLink httpnsAdobeComadobecloudrelcertificates) {
    this.httpnsAdobeComadobecloudrelcertificates = httpnsAdobeComadobecloudrelcertificates;
  }

  public ProgramLinks httpnsAdobeComadobecloudreldomainNames(HalLink httpnsAdobeComadobecloudreldomainNames) {
    this.httpnsAdobeComadobecloudreldomainNames = httpnsAdobeComadobecloudreldomainNames;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudreldomainNames
   * @return httpnsAdobeComadobecloudreldomainNames
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudreldomainNames() {
    return httpnsAdobeComadobecloudreldomainNames;
  }

  public void setHttpnsAdobeComadobecloudreldomainNames(HalLink httpnsAdobeComadobecloudreldomainNames) {
    this.httpnsAdobeComadobecloudreldomainNames = httpnsAdobeComadobecloudreldomainNames;
  }

  public ProgramLinks httpnsAdobeComadobecloudreltenant(HalLink httpnsAdobeComadobecloudreltenant) {
    this.httpnsAdobeComadobecloudreltenant = httpnsAdobeComadobecloudreltenant;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudreltenant
   * @return httpnsAdobeComadobecloudreltenant
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudreltenant() {
    return httpnsAdobeComadobecloudreltenant;
  }

  public void setHttpnsAdobeComadobecloudreltenant(HalLink httpnsAdobeComadobecloudreltenant) {
    this.httpnsAdobeComadobecloudreltenant = httpnsAdobeComadobecloudreltenant;
  }

  public ProgramLinks httpnsAdobeComadobecloudrelnetworkInfrastructures(HalLink httpnsAdobeComadobecloudrelnetworkInfrastructures) {
    this.httpnsAdobeComadobecloudrelnetworkInfrastructures = httpnsAdobeComadobecloudrelnetworkInfrastructures;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelnetworkInfrastructures
   * @return httpnsAdobeComadobecloudrelnetworkInfrastructures
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelnetworkInfrastructures() {
    return httpnsAdobeComadobecloudrelnetworkInfrastructures;
  }

  public void setHttpnsAdobeComadobecloudrelnetworkInfrastructures(HalLink httpnsAdobeComadobecloudrelnetworkInfrastructures) {
    this.httpnsAdobeComadobecloudrelnetworkInfrastructures = httpnsAdobeComadobecloudrelnetworkInfrastructures;
  }

  public ProgramLinks httpnsAdobeComadobecloudrelregions(HalLink httpnsAdobeComadobecloudrelregions) {
    this.httpnsAdobeComadobecloudrelregions = httpnsAdobeComadobecloudrelregions;
    return this;
  }

   /**
   * Get httpnsAdobeComadobecloudrelregions
   * @return httpnsAdobeComadobecloudrelregions
  **/
  @Schema(description = "")
  public HalLink getHttpnsAdobeComadobecloudrelregions() {
    return httpnsAdobeComadobecloudrelregions;
  }

  public void setHttpnsAdobeComadobecloudrelregions(HalLink httpnsAdobeComadobecloudrelregions) {
    this.httpnsAdobeComadobecloudrelregions = httpnsAdobeComadobecloudrelregions;
  }

  public ProgramLinks self(HalLink self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(description = "")
  public HalLink getSelf() {
    return self;
  }

  public void setSelf(HalLink self) {
    this.self = self;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgramLinks programLinks = (ProgramLinks) o;
    return Objects.equals(this.httpnsAdobeComadobecloudrelpipelines, programLinks.httpnsAdobeComadobecloudrelpipelines) &&
        Objects.equals(this.httpnsAdobeComadobecloudrelenvironments, programLinks.httpnsAdobeComadobecloudrelenvironments) &&
        Objects.equals(this.httpnsAdobeComadobecloudrelrepositories, programLinks.httpnsAdobeComadobecloudrelrepositories) &&
        Objects.equals(this.httpnsAdobeComadobecloudrelipAllowlists, programLinks.httpnsAdobeComadobecloudrelipAllowlists) &&
        Objects.equals(this.httpnsAdobeComadobecloudrelcertificates, programLinks.httpnsAdobeComadobecloudrelcertificates) &&
        Objects.equals(this.httpnsAdobeComadobecloudreldomainNames, programLinks.httpnsAdobeComadobecloudreldomainNames) &&
        Objects.equals(this.httpnsAdobeComadobecloudreltenant, programLinks.httpnsAdobeComadobecloudreltenant) &&
        Objects.equals(this.httpnsAdobeComadobecloudrelnetworkInfrastructures, programLinks.httpnsAdobeComadobecloudrelnetworkInfrastructures) &&
        Objects.equals(this.httpnsAdobeComadobecloudrelregions, programLinks.httpnsAdobeComadobecloudrelregions) &&
        Objects.equals(this.self, programLinks.self);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpnsAdobeComadobecloudrelpipelines, httpnsAdobeComadobecloudrelenvironments, httpnsAdobeComadobecloudrelrepositories, httpnsAdobeComadobecloudrelipAllowlists, httpnsAdobeComadobecloudrelcertificates, httpnsAdobeComadobecloudreldomainNames, httpnsAdobeComadobecloudreltenant, httpnsAdobeComadobecloudrelnetworkInfrastructures, httpnsAdobeComadobecloudrelregions, self);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProgramLinks {\n");
    
    sb.append("    httpnsAdobeComadobecloudrelpipelines: ").append(toIndentedString(httpnsAdobeComadobecloudrelpipelines)).append("\n");
    sb.append("    httpnsAdobeComadobecloudrelenvironments: ").append(toIndentedString(httpnsAdobeComadobecloudrelenvironments)).append("\n");
    sb.append("    httpnsAdobeComadobecloudrelrepositories: ").append(toIndentedString(httpnsAdobeComadobecloudrelrepositories)).append("\n");
    sb.append("    httpnsAdobeComadobecloudrelipAllowlists: ").append(toIndentedString(httpnsAdobeComadobecloudrelipAllowlists)).append("\n");
    sb.append("    httpnsAdobeComadobecloudrelcertificates: ").append(toIndentedString(httpnsAdobeComadobecloudrelcertificates)).append("\n");
    sb.append("    httpnsAdobeComadobecloudreldomainNames: ").append(toIndentedString(httpnsAdobeComadobecloudreldomainNames)).append("\n");
    sb.append("    httpnsAdobeComadobecloudreltenant: ").append(toIndentedString(httpnsAdobeComadobecloudreltenant)).append("\n");
    sb.append("    httpnsAdobeComadobecloudrelnetworkInfrastructures: ").append(toIndentedString(httpnsAdobeComadobecloudrelnetworkInfrastructures)).append("\n");
    sb.append("    httpnsAdobeComadobecloudrelregions: ").append(toIndentedString(httpnsAdobeComadobecloudrelregions)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
