/*
 * Cloud Manager API
 * This API allows access to Cloud Manager programs, pipelines, and environments by an authorized technical account created through the Adobe I/O Console. The base url for this API is https://cloudmanager.adobe.io, e.g. to get the list of programs for an organization, you would make a GET request to https://cloudmanager.adobe.io/api/programs (with the correct set of headers as described below). This swagger file can be downloaded from https://raw.githubusercontent.com/AdobeDocs/cloudmanager-api-docs/main/swagger-specs/api.yaml.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.adobe.aio.cloudmanager.impl.model;

/*-
 * #%L
 * Adobe Cloud Manager Client Library
 * %%
 * Copyright (C) 2020 - 2022 Adobe Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import java.util.Arrays;
import com.adobe.aio.cloudmanager.impl.model.Organisation;
import com.adobe.aio.cloudmanager.impl.model.TenantLinks;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * Describes a __Tenant__
 */
@Schema(description = "Describes a __Tenant__")

public class Tenant implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("imsOrgId")
  private String imsOrgId = null;

  @JsonProperty("imsTenantId")
  private String imsTenantId = null;

  @JsonProperty("description")
  private String description = null;

  /**
   * Status of the tenant
   */
  public enum StatusEnum {
    CREATING("creating"),
    READY("ready"),
    FAILED("failed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("organisation")
  private Organisation organisation = null;

  @JsonProperty("_links")
  private TenantLinks _links = null;

  public Tenant id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the tenant
   * @return id
  **/
  @Schema(example = "14", description = "Identifier of the tenant")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Tenant imsOrgId(String imsOrgId) {
    this.imsOrgId = imsOrgId;
    return this;
  }

   /**
   * IMS Organization of this tenant
   * @return imsOrgId
  **/
  @Schema(example = "1AAA222B3C4444D55E666666@AdobeOrg", required = true, description = "IMS Organization of this tenant")
  public String getImsOrgId() {
    return imsOrgId;
  }

  public void setImsOrgId(String imsOrgId) {
    this.imsOrgId = imsOrgId;
  }

  public Tenant imsTenantId(String imsTenantId) {
    this.imsTenantId = imsTenantId;
    return this;
  }

   /**
   * IMS Tenant Id
   * @return imsTenantId
  **/
  @Schema(example = "acmeCorp", required = true, description = "IMS Tenant Id")
  public String getImsTenantId() {
    return imsTenantId;
  }

  public void setImsTenantId(String imsTenantId) {
    this.imsTenantId = imsTenantId;
  }

  public Tenant description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the tenant
   * @return description
  **/
  @Schema(example = "Description for acmeCorp", description = "Description of the tenant")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Tenant status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the tenant
   * @return status
  **/
  @Schema(example = "creating", description = "Status of the tenant")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Tenant organisation(Organisation organisation) {
    this.organisation = organisation;
    return this;
  }

   /**
   * Get organisation
   * @return organisation
  **/
  @Schema(description = "")
  public Organisation getOrganisation() {
    return organisation;
  }

  public void setOrganisation(Organisation organisation) {
    this.organisation = organisation;
  }

  public Tenant _links(TenantLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public TenantLinks getLinks() {
    return _links;
  }

  public void setLinks(TenantLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tenant tenant = (Tenant) o;
    return Objects.equals(this.id, tenant.id) &&
        Objects.equals(this.imsOrgId, tenant.imsOrgId) &&
        Objects.equals(this.imsTenantId, tenant.imsTenantId) &&
        Objects.equals(this.description, tenant.description) &&
        Objects.equals(this.status, tenant.status) &&
        Objects.equals(this.organisation, tenant.organisation) &&
        Objects.equals(this._links, tenant._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, imsOrgId, imsTenantId, description, status, organisation, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tenant {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imsOrgId: ").append(toIndentedString(imsOrgId)).append("\n");
    sb.append("    imsTenantId: ").append(toIndentedString(imsTenantId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    organisation: ").append(toIndentedString(organisation)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
