name: Update Changelog

concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.repository == 'adobe/aio-lib-java-cloudmanager' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set From Tag
        id: set_from_tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "fromTag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build Changelog Fragment
        id: build_changelog_fragment
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: ".github/.intermediate-changelog-config.json"
          fromTag: ${{steps.set_from_tag.outputs.fromTag}}
          toTag: HEAD
          outputfile: fragment.md

      - name: Build Changelog
        if: steps.build_changelog_fragment.outputs.changelog != '- no changes'
        run: |
          sed -i '/^#.*Changelog/,/## \[aio-lib-java-cloudmanager/{
          /^#.*Changelog/p
          /^#.*Changelog/a\
          
          /^#.*Changelog/r fragment.md
          
          /^## \[aio-lib-java-cloudmanager/! d
          
          /## \[aio-lib-java-cloudmanager/i\
        
          }' CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add CHANGELOG.md
          git commit -m 'Update Changelog.'
          git push
