name: Javadoc Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-javadocs:
    runs-on: ubuntu-latest

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Set up dependency cache
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build & Verify
      - name: Build & Test with Maven
        run: mvn -B clean package -P generate-javadoc

      - name: Check For Javadocs
        id: javadoc-check
        run: git diff
