name: Javadoc Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-javadocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test with Maven
        run: mvn -B clean package -P generate-javadoc

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Add any JavaDoc Updates
        id: add-javadoc
        run: |
          git add docs/apidocs
          git commit -m "Add JavaDoc updates."
          git push

